# Generated by Django 6.0.6 on 2026-07-02 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الترخيص')),
                ('firm_name', models.CharField(blank=True, max_length=255, verbose_name='اسم شركة الوساطة')),
                ('commission_rate', models.DecimalField(decimal_places=3, default=0.5, max_digits=5, verbose_name='نسبة العمولة %')),
                ('status', models.CharField(choices=[('pending', 'قيد التفعيل'), ('active', 'نشط'), ('suspended', 'موقوف')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سمسار',
                'verbose_name_plural': 'السماسرة',
                'db_table': 'brokers',
            },
        ),
        migrations.CreateModel(
            name='BrokerClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='brokers.broker')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عميل سمسار',
                'verbose_name_plural': 'عملاء السماسرة',
                'db_table': 'broker_clients',
                'unique_together': {('broker', 'client')},
            },
        ),
    ]
