# Generated by Django 6.0.6 on 2026-07-02 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='الرمز')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('day_high', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('day_low', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('volume_today', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='companies.company')),
            ],
            options={
                'verbose_name': 'سهم',
                'verbose_name_plural': 'الأسهم',
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('buy', 'شراء'), ('sell', 'بيع')], max_length=10)),
                ('quantity', models.BigIntegerField()),
                ('filled_quantity', models.BigIntegerField(default=0)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('partially_filled', 'منفَّذ جزئيًا'), ('filled', 'منفَّذ بالكامل'), ('cancelled', 'مُلغى')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_orders', to='brokers.broker')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.stock')),
            ],
            options={
                'verbose_name': 'أمر تداول',
                'verbose_name_plural': 'أوامر التداول',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='market.order')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='market.order')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market.stock')),
            ],
            options={
                'verbose_name': 'صفقة',
                'verbose_name_plural': 'الصفقات',
                'db_table': 'trades',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market.stock')),
            ],
            options={
                'verbose_name': 'سجل سعري',
                'verbose_name_plural': 'السجلات السعرية',
                'db_table': 'price_history',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
