# Generated by Django 6.0.6 on 2026-07-02 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255, verbose_name='الاسم القانوني للشركة')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم التجاري')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='رقم السجل التجاري')),
                ('sector', models.CharField(max_length=100, verbose_name='القطاع الاقتصادي')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True)),
                ('listing_status', models.CharField(choices=[('draft', 'مسودة'), ('pending_review', 'قيد المراجعة'), ('listed', 'مُدرجة'), ('suspended', 'موقوفة'), ('delisted', 'مشطوبة')], default='draft', max_length=20)),
                ('total_shares_issued', models.BigIntegerField(default=0, verbose_name='إجمالي الأسهم المُصدرة')),
                ('nominal_share_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='القيمة الاسمية للسهم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('quarterly', 'ربع سنوي'), ('annual', 'سنوي')], max_length=20)),
                ('fiscal_period', models.CharField(help_text='مثال: Q1 2026', max_length=50, verbose_name='الفترة المالية')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('document', models.FileField(upload_to='financial_reports/%Y/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='companies.company')),
            ],
            options={
                'verbose_name': 'تقرير مالي',
                'verbose_name_plural': 'التقارير المالية',
                'db_table': 'financial_reports',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_shares', models.BigIntegerField()),
                ('requested_price_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('submitted', 'مُقدَّم'), ('under_review', 'قيد الدراسة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='submitted', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_requests', to='companies.company')),
            ],
            options={
                'verbose_name': 'طلب إدراج',
                'verbose_name_plural': 'طلبات الإدراج',
                'db_table': 'listing_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
