# Generated by Django 6.0.6 on 2026-07-02 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrequest',
            name='requested_symbol',
            field=models.CharField(blank=True, help_text='حروف إنجليزية و/أو أرقام فقط، من حرفين إلى 6 أحرف (مثال: BZRK). إن تُرك فارغًا سيولّده النظام تلقائيًا.', max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,6}$', 'استخدم حروفًا إنجليزية كبيرة و/أو أرقامًا فقط (2-6 خانات).')], verbose_name='رمز السهم المقترح (Ticker)'),
        ),
    ]
